# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5430:5432'

volumes:
  postgres:
